

server:
  port: 80 #端口号

spring:
  application:
    name: cloud-order-service  #服务名
  cloud:
    consul:
      host: localhost      #consul的IP
      port: 8500           #consul启动端口默认8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true     #不写这个配置，在docker下的consul里面健康检查会失败
        healthCheckInterval: 5s     #健康检查频率
        port: ${server.port}        #注册服务所在端口

ribbon:
  ReadTimeout: 5000  #请求处理的超时时间 5秒
  ConnectTimeout: 3000   #请求连接的超时时间 3秒

logging:
  level:
    top.msxdlb.springcloud.service.OrderService: debug  #日志打印级别