

server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cloud_2020?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#  cloud:
#    zookeeper:
#      connect-string: 192.168.1.130:2181
mybatis-plus:
  #实体扫描,多个package用逗号或者分号分隔
  typeAliasesPackage: com.atguigu.sprigncloud.entity  #所有entity别名类所在包