

server:
  port: 80 #端口号

spring:
  application:
    name: cloud-hystrix-consumer-service  #服务名
  cloud:
    consul:
      host: localhost      #consul的IP
      port: 8500           #consul启动端口默认8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true     #不写这个配置，在docker下的consul里面健康检查会失败
        healthCheckInterval: 5s     #健康检查频率
        port: ${server.port}        #注册服务所在端口

feign:
  hystrix:
    enabled: true #在feign中开启 Hystrix(熔断器)